controller:
  replicaCount: 2
  config:
    use-forwarded-headers: "true"

  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: "app"
                operator: In
                values:
                - nginx-ingress
              - key: "component"
                operator: In
                values:
                - controller

          topologyKey: "kubernetes.io/hostname"
