---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{.Release.Name }}-frontend-ingress-nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    external-dns.alpha.kubernetes.io/hostname: "code-basics.com.,ru.code-basics.com., code-basics.ru."

spec:
  rules:
    - host: "*.code-basics.com"
      http:
        paths:
          - backend:
              serviceName: "{{.Release.Name }}-frontend-service"
              servicePort: 8080
    - host: "code-basics.com"
      http:
        paths:
          - backend:
              serviceName: "{{.Release.Name }}-frontend-service"
              servicePort: 8080
    - host: "code-basics.ru"
      http:
        paths:
          - backend:
              serviceName: "{{.Release.Name }}-frontend-service"
              servicePort: 8080
