---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{.Release.Name }}-2-frontend-ingress"
spec:
  backend:
    serviceName: "{{.Release.Name }}-frontend-service"
    servicePort: 8080
