---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: "*.code-basics.com"
      http:
        paths:
          - backend:
              serviceName: "{{.Release.Name }}-frontend-service"
              servicePort: 8080
    - host: "code-basics.com"
      http:
        paths:
          - backend:
              serviceName: "{{.Release.Name }}-frontend-service"
              servicePort: 8080
    - host: "code-basics.ru"
      http:
        paths:
          - backend:
              serviceName: "{{.Release.Name }}-frontend-service"
              servicePort: 8080
