---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    # https://stackoverflow.com/questions/40791459/upstream-sent-too-big-header-while-reading-response-header-from-upstream
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4 256k"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
spec:
  rules:
    - host: "*.code-basics.com"
      http:
        paths:
          - backend:
              serviceName: "{{.Release.Name }}-frontend-service"
              servicePort: 8080
    - host: "code-basics.com"
      http:
        paths:
          - backend:
              serviceName: "{{.Release.Name }}-frontend-service"
              servicePort: 8080
    - host: "code-basics.ru"
      http:
        paths:
          - backend:
              serviceName: "{{.Release.Name }}-frontend-service"
              servicePort: 8080
