# https://stackoverflow.com/questions/40791459/upstream-sent-too-big-header-while-reading-response-header-from-upstream
apiVersion: v1
data:
  proxy-buffers: "4 256k"
  proxy-buffer-size: "128k"
  proxy-busy-buffers-size: "256k"

kind: ConfigMap
metadata:
  name: nginx-ingress-nginx-ingress
  namespace: default
